// data.js
export const siteData = {
  name: 'Prem Kumar',
  role: 'Software Engineer | Full-stack Developer',
  titles: [
    'AI & Data Science Specialist',
    'Front End Developer',
    'Open Source Contributor'
  ],
  shortBio: 'I build fast, accessible web apps and data-driven solutions with a touch of creativity.',
  about: `I’m Prem Kumar — a final-year B.Tech student and aspiring Software Engineer passionate about building fast, reliable, and user-focused solutions. I thrive at the intersection of problem-solving and creativity, whether it’s designing scalable backend systems, crafting intuitive frontends, or exploring cutting-edge algorithms.
          My experience spans projects like full-stack applications, AI-powered tools, optimization models, and C++ systems programming. I enjoy tackling complex challenges — from graph analytics to machine learning pipelines — and turning them into elegant, efficient code. Currently, I’m honing my skills in C++, Python, SQL, and React, with a keen interest in big data systems, distributed computing, and performance optimization. Beyond coding, I value clean design, measurable impact, and collaboration that pushes ideas forward.`,
  resume: '/interactive_resume.html',
  social: {
    github: 'https://github.com/premkumaranubhav123  ',
    linkedin: 'https://www.linkedin.com/in/prem-kumar007  ',
    email: 'premkumar39411@gmail.com',
    phone: '+91 9386225649',
    portfolio: 'https://prem-kumar-portfolio-anubhav-007.netlify.app/  ',
  },
  theme: {
    primary: 'teal-500',
    accent: 'indigo-500',
    font: 'Inter, system-ui, sans-serif',
  },
  navLinks: [
    { url: '#experience', name: 'Experience' },
    { url: '#projects', name: 'Projects' },
    { url: '#about', name: 'About' },
    { url: '#contact', name: 'Contact' },
  ],
  experience: [
    {
      company: 'Citadel',
      role: 'Software Engineering Intern',
      duration: 'May 2025 – Jun 2025 (Remote)',
      responsibilities: [
        'Built high-frequency trading simulator (~100K trades/sec, latency < 5ms)',
        'Led team of 4 to optimize ingestion with Kafka & Redis (−35% lag)',
        'Standardized CI/CD with GitHub Actions & Docker (+40% release reliability)',
      ],
      link: '/interactive_resume.html#experience',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      title: 'Automated Grading Tool',
      description: 'Developed a Tkinter-based grading system that processes 150+ student records, reducing manual grading time by 50%.',
      tech: ['Python', 'Tkinter', 'Pandas', 'Matplotlib'],
      repo: 'https://github.com/premkumaranubhav123/Automated-Grading-Tool  ',
      live: 'https://smart-grading-app-for-grading.streamlit.app/  ',
      img: '/project/project1.png',
    },
    {
      id: 'proj-2',
      title: 'Packet Analyzer Dashboard',
      description: 'Dash-based visualization tool processing 500 packets/sec with 92% anomaly detection accuracy and reduced false positives by 20%.',
      tech: ['Python', 'Dash', 'Concurrency'],
      repo: 'https://github.com/premkumaranubhav123/network-packet-hosting  ',
      img: '/project/project2.png',
    },
    {
      id: 'proj-3',
      title: 'Language Learning Bot',
      description: 'NLP chatbot using seq2seq and RNN models achieving 85% BLEU score, with Flask backend serving 500+ daily queries.',
      tech: ['TensorFlow', 'Flask', 'JavaScript'],
      repo: 'https://github.com/premkumaranubhav123/language-learning-bot  ',
      live: 'https://language-learning-bot-updated.onrender.com/  ',
      img: '/project/project3.png',
    },
    {
      id: 'proj-4',
      title: 'Stock-Price_Tracker',
      description: 'Built a real-time stock price visualization tool using Python, Dash, and yfinance. Skills: Data fetching, API integration, interactive UI development.',
      tech: ['Python', 'data visualization, and cloud deployment.'],
      repo: 'https://github.com/premkumaranubhav123/stock-tracker  ',
      img: '/project/project4.png',
    },
    {
      id: 'proj-5',
      title: 'credit-card-fraud-detection',
      description: 'ML-based fraud detection web app analyzing credit card transactions with adjustable sensitivity, built using Python, Streamlit, and scikit-learn.',
      tech: ['Python', 'Scikit-learn', 'Tensorflow'],
      repo: 'https://github.com/premkumaranubhav123/credit-card-fraud-detection  ',
      live: '',
      img: '/project/project5.png',
    },
    {
      id: 'proj-6',
      title: 'Quiz Maker',
      description: 'An interactive web-based application for creating and taking quizzes, built as part of the GrowthLink Web Development Assignment.',
      tech: ['Html', 'CSS', 'JavaScript'],
      repo: 'https://github.com/premkumaranubhav123/quiz-maker  ',
      live: 'https://quiz-maker-growth-link.netlify.app/  ',
      img: '/project/project6.png',
    },
  ],
  skills: [
    'Python',
    'C++',
    'Java',
    'SQL',
    'React',
    'Node.js',
    'JavaScript',
    'ML',
    'Flask',
    'TensorFlow',
    'Git',
    'Docker',
    'Kafka',
    'Redis',
    'Git',
    'Linux'
  ],
  profilePicture: '/favicon.jpg',
};
